routes/web.php
<?php
//Auth
Auth::routes([
	'verify' => false,
	'register' => false
]);

Route::get('image/{filename}', 'AdminController@displayImage')->name('image.displayImage');

//Front
Route::get('/','FrontController@index')->name('front.index');
Route::get('noticias/{cat}/{name}','FrontController@single')->name('front.single');
Route::get('categoria/{cat}','FrontController@category')->name('front.category');
Route::get('categorias/{user}/{name}','FrontController@categoryUser')->name('front.category.user');
Route::get('contacto','FrontController@contact')->name('front.contact');
Route::get('busqueda','FrontController@search')->name('front.search');
Route::any('banners/{id}/{position}','FrontController@url')->name('front.url');
Route::post('save_contact','FrontController@save_contact')->name('front.save.contact');

//Admin
Route::group(['prefix' => 'admin'], function(){
	Route::get('/','AdminController@index')->name('admin.index');
	Route::post('users/upload','UserController@upload_image')->name('upload.user');
    Route::resource('users','UserController');
	Route::resource('leads','LeadController');
	Route::resource('clients','ClientController');
	Route::resource('clientspost','ClientPostController');
	Route::post('uploads/lateral','BannerController@lateral')->name('upload.lateral');
	Route::post('uploads/full','BannerController@full')->name('upload.full');
	Route::post('uploads/detail','BannerController@detail')->name('upload.detail');
	Route::post('uploads/modal','BannerController@modal')->name('upload.modal');
	Route::resource('banners','BannerController');
	Route::post('uploads/image','PostController@upload_image')->name('upload.image');
	Route::get('posts/list','PostController@getPosts')->name('posts.list');
	Route::get('posts/delete/{id}','PostController@delete')->name('posts.delete');
	Route::get('post/restore/{id}','PostController@restore')->name('post.restore');
	Route::resource('posts','PostController');
	Route::resource('systems','SystemController');
	Route::resource('categories','CategoryController');

	//Gallery
	Route::post('uploads/gallery','GalleryController@upload_gallery')->name('upload.gallery');
	Route::any('remove/gallery','GalleryController@destroy')->name('destroy.gallery');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Client.php
<?php

namespace App;
use App\ClientPost;
use App\Post;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    public function posts()
    {
    	return $this->hasMany(Post::class, 'id', 'post_id');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Post;
use App\Banner;
use App\ClientPost;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $data = [
            'users' => User::role('cliente')->get(),
        ];

        return view('admin.client.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $posts = ClientPost::where('client_id',$id)->get();
        $banners = Banner::where('user_id',$id)->get();
        $posts_modal = Post::get();

        return view('admin.client.edit',compact('user','posts','posts_modal','banners'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->update($request->except('_token','_method'));

        // Le asignamos el rol de Cliente
        if ($request->rol == 'editor') {
            $user->syncRoles('editor');
        } elseif($request->rol == 'columnista') {
            $user->syncRoles('columnista');
        } elseif($request->rol == 'cliente') {
            $user->syncRoles('cliente');
        } else {
            $user->syncRoles('admin');
        }

        return redirect()->back()->with('msg-success','Se actualizo la información.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('clients.index')->with('msg-success','Se ha borrado el usuario correctamente.');
    }
}

resources/views/admin/client/create.blade.php
@extends('layouts.admin')

@section('title','Agregar usuario')

@section('add-button')
	<a href="{{route('users.index')}}" class="btn btn-info">Regresar</a>
@endsection

@section('subtitle')
@endsection

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Usuario</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
	
	<form method="post" action="{{route('users.store')}}">
		@csrf
		<div class="form-group">
			<label>Nombre:</label>
			<input type="text" name="name" class="form-control" required>
		</div>
		<div class="form-group">
			<label>Correo electrónico:</label>
			<input type="email" name="email" class="form-control" required>
		</div>
		<div class="form-group">
			<label>Rol:</label>
			<select class="form-control" name="rol" required>
				<option value="admin">Administrador</option>
				<option value="editor">Editor</option>
				<option value="columnista">Columnista</option>
				<option value="cliente">Cliente</option>
			</select>
		</div>
		<div class="form-group">
			<label>Contraseña:</label>
			<input type="password" name="password" class="form-control" required>
		</div>
		<button type="submit" class="btn btn-success">Agregar usuario</button>
	</form>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
	<script src="{{asset('assets/plugins/summernote/summernote-bs4.min.js')}}"></script>
	<script>
		switch_init();
		summernote_init();
	</script>
@endpush

resources/views/admin/client/edit.blade.php
@extends('layouts.admin')

@section('title','Editar cliente')

@section('add-button')
	<a href="{{route('clients.index')}}" class="btn btn-danger" style="margin-right: 5px;">Cancelar</a>
	<a href="#" id="save" class="btn btn-success">Guardar cambios</a>
@endsection

@section('subtitle')
@endsection

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Clientes</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">

  	<style>
  		.banners ul {
  			display: inline-block;
  			margin:0 auto;
  			text-align: center;
  		}

  		.banners ul li {
  			list-style-type: none;
  			display: inline-block;
  		}
  	</style>
@endpush

@section('content')
	
	@if (Session::has('msg-success'))
	    <div class="alert alert-success">
	        <ul>
	            <li>{!! Session::get('msg-success') !!}</li>
	        </ul>
	    </div>
	@endif
	<form method="post" id="form-global" action="{{route('clients.update',$user->id)}}">
		@if ($errors->any())
	     	@foreach ($errors->all() as $error)
	           <div>{{$error}}</div>
	     	@endforeach
		@endif
		@csrf
		{{ method_field('PUT') }}
		<div class="row">
			<div class="col-lg-12">
				<div class="form-group">
					<label>Nombre:</label>
					<input type="text" name="name" class="form-control" value="{{$user->name}}" required>
				</div>`
			</div>
			<div class="col-lg-3">
				<div class="form-group">
					<label>Correo electrónico:</label>
					<input type="text" name="email" class="form-control" value="{{$user->email}}" required>
				</div>
			</div>
			@role('admin')
				<div class="col-lg-3">
					<div class="form-group">
						<label>Roles:</label>
						<select class="form-control" name="rol" required>
							<option value="admin">Administrador</option>
							<option value="editor">Editor</option>
							<option value="columnista">Columnista</option>
							<option value="cliente" selected>Cliente</option>
						</select>
					</div>
				</div>
			@endrole
			<div class="col-lg-3">
				<div class="form-group">
					<label>RFC:</label>
					<input type="text" name="rfc" class="form-control" value="{{$user->rfc}}">
				</div>
			</div>
			<div class="col-lg-3">
				<div class="form-group">
					<label>Teléfono:</label>
					<input type="tel" name="phone" class="form-control" value="{{$user->phone}}">
				</div>
			</div>
			<div class="col-lg-12">
				<div class="form-group">
					<label>Dirección:</label>
					<textarea class="form-control" name="direction">{{$user->direction}}</textarea>
				</div>
			</div>
		</div>
		
		<button type="submit" class="btn btn-success btn-hidden">Guardar</button>
	</form>

	<h2>Noticias</h2>

	<table class="datatable table table-striped table-sm">
      <thead class="thead-light">
          <tr class="text-center">
            <th>Nombre</th>
            <th>Fecha de creación</th>
            <th>Visitas</th>
            <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
      		@foreach ($posts as $post)
	            <tr class="text-center">
	                <td>{{$post->post->name}}</td>
	                <td>{{$post->post->date}}</td>
	                <td>
            			<span class="badge badge-warning">{{$post->post->view}}</span>
	                </td>
	                <td>
            			<form method="POST" action="{{ route('clientspost.destroy',$post->id) }}">
						    @csrf
						    <input type="hidden" name="id" value="{{$post->id}}">
						    {{ method_field('delete') }}
						    <button type="submit" class="btn btn-danger btn-xs">Eliminar</button> 
						</form>
	                </td>
	            </tr>
            @endforeach
      </tbody>
    </table>
    <hr>

    <a href="#modal-article" data-fancybox class="btn btn-primary">Asignar artículo</a>

    <div id="modal-article" style="width: 70%;display: none;">
    	<div class="container">
    		<div class="row">
    			<div class="col-lg-12">
    				<h3>Asignar artículo</h3>
    				<hr>
    				<table id="datatable" class="table table-striped table-bordered table-sm">
				      <thead class="thead-light">
				          <tr class="text-center">
				            <th>Nombre</th>
				            <th>Fecha</th>
				            <th>Acciones</th>
				          </tr>
				      </thead>
				      <tbody>
				      		@foreach ($posts_modal as $post)
					            <tr class="text-center">
					                <td>{{$post->CutTitle}}</td>
					                <td>{{$post->date}}</td>
					                <td>
					                	<ul>
					                		<li>
					                			<form action="{{route('clientspost.store')}}" method="post">
					                				@csrf
					                				<input type="hidden" value="{{$post->id}}" name="id">
					                				<input type="hidden" value="{{$user->id}}" name="client_id">
					                				<button type="submit" class="btn btn-success btn-xs">Asignar</button>
					                			</form>
					                		</li>
					                	</ul>
					                </td>
					            </tr>
				            @endforeach
				      </tbody>
				    </table>
    			</div>
    		</div>
    	</div>
    </div>

    <hr>
    <h2>Banners de publicidad</h2>

	<table class="datatable table table-striped table-sm banners">
      <thead class="thead-light">
          <tr class="text-center">
            <th>Nombre</th>
            <th>Cliente</th>
            <th>Fecha</th>
            <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
      		@foreach ($banners as $banner)
	            <tr class="text-center">
	                <td>{{$banner->name}}</td>
	                <td>{{$banner->client->name}}</td>
	                <td>{{$banner->created_at->format('d-m-Y')}}</td>
	                <td>
	                	<ul>
	                		<li>
	                			<a href="{{route('banners.edit',$banner->id)}}" class="btn btn-success btn-xs">Editar</a>
	                		</li>
	                		@role('admin')
	                		<li>
	                			<form method="POST" action="{{ route('banners.destroy',$banner->id) }}">
								    @csrf
								    {{ method_field('delete') }}
								    <button type="submit" class="btn btn-danger btn-xs">Eliminar</button> 
								</form>	
	                		</li>
	                		@endrole
	                	</ul>
	                </td>
	            </tr>
            @endforeach
      </tbody>
    </table>
    <hr>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
	<script src="{{asset('adminlte/plugins/datatables/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
	<script>
	 	datatables();
	 	datatabless();
	</script>
@endpush

resources/views/admin/client/index.blade.php
@extends('layouts.admin')

@section('title','Clientes')

@section('subtitle','Todos los usuarios')

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Clientes</li>
@endsection

@section('add-button')
	<li class="nav-item d-none d-sm-inline-block">
	    <a href="{{route('users.create')}}" class="btn btn-success" style="color:#fff;">Agregar</a>
	</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')
	@if (Session::has('msg-success'))
	    <div class="alert alert-success">
	        <ul>
	            <li>{!! Session::get('msg-success') !!}</li>
	        </ul>
	    </div>
	@endif
	<table id="datatable" class="table table-striped table-bordered table-sm">
      <thead class="thead-light">
          <tr class="text-center">
          	<th>#</th>
            <th>Nombre</th>
            <th>Fecha de registro</th>
            <th>Rol</th>
            <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
      		@foreach ($data['users'] as $user)
	            <tr class="text-center">
	            	<td>{{$user->id}}</td>
	                <td>{{$user->name}}</td>
	                <td>{{$user->date}}</td>
	                <td>
            			<span class="badge badge-warning">Cliente</span>
	                </td>
	                <td>
	                	<ul>
	                		<li>
	                			<a href="{{route('clients.edit',$user->id)}}" class="btn btn-success btn-xs">Editar</a>
	                		</li>
	                		<li>
	                			<form method="POST" action="{{ route('clients.destroy',$user->id) }}">
								    @csrf
								    {{ method_field('delete') }}
								    <button type="submit" class="btn btn-danger btn-xs">Eliminar</button> 
								</form>	
	                		</li>
	                	</ul>
	                </td>
	            </tr>
            @endforeach
      </tbody>
    </table>
@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('adminlte/plugins/datatables/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
	<script>
	  datatables();
	</script>
@endpush

resources/views/admin/client/show.blade.php
@extends('layouts.admin')

@section('title',$post->name)

@section('col','col-12')

@section('subtitle')
	<strong>Fecha de creación:</strong> {{$post->created_at->format('d-m-Y')}}
@endsection

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item"><a href="{{route('posts.index')}}">Noticias</a></li>
  <li class="breadcrumb-item active">{{$post->name}}</li>
@endsection

@section('content')
	<p>
		<strong>Nombre:</strong> {{$post->name}}<br>
		<strong>Estatus:</strong> {{$post->status}}<br>
		<strong>Categoría:</strong> {{$post->name}}<br>
		<strong>Imagen:</strong> {{$post->img}}<br>
		<strong>Descripción:</strong> <br>{{$post->description}}
	</p>
@endsection

@section('footer')
	<a href="{{route('posts.index')}}" class="btn btn-info">Regresar</a>
@endsection

@push('js')
@endpush