routes/web.php
<?php
//Auth
Auth::routes([
	'verify' => false,
	'register' => false
]);

Route::get('image/{filename}', 'AdminController@displayImage')->name('image.displayImage');

//Front
Route::get('/','FrontController@index')->name('front.index');
Route::get('noticias/{cat}/{name}','FrontController@single')->name('front.single');
Route::get('categoria/{cat}','FrontController@category')->name('front.category');
Route::get('categorias/{user}/{name}','FrontController@categoryUser')->name('front.category.user');
Route::get('contacto','FrontController@contact')->name('front.contact');
Route::get('busqueda','FrontController@search')->name('front.search');
Route::any('banners/{id}/{position}','FrontController@url')->name('front.url');
Route::post('save_contact','FrontController@save_contact')->name('front.save.contact');

//Admin
Route::group(['prefix' => 'admin'], function(){
	Route::get('/','AdminController@index')->name('admin.index');
	Route::post('users/upload','UserController@upload_image')->name('upload.user');
    Route::resource('users','UserController');
	Route::resource('leads','LeadController');
	Route::resource('clients','ClientController');
	Route::resource('clientspost','ClientPostController');
	Route::post('uploads/lateral','BannerController@lateral')->name('upload.lateral');
	Route::post('uploads/full','BannerController@full')->name('upload.full');
	Route::post('uploads/detail','BannerController@detail')->name('upload.detail');
	Route::post('uploads/modal','BannerController@modal')->name('upload.modal');
	Route::resource('banners','BannerController');
	Route::post('uploads/image','PostController@upload_image')->name('upload.image');
	Route::get('posts/list','PostController@getPosts')->name('posts.list');
	Route::get('posts/delete/{id}','PostController@delete')->name('posts.delete');
	Route::get('post/restore/{id}','PostController@restore')->name('post.restore');
	Route::resource('posts','PostController');
	Route::resource('systems','SystemController');
	Route::resource('categories','CategoryController');

	//Gallery
	Route::post('uploads/gallery','GalleryController@upload_gallery')->name('upload.gallery');
	Route::any('remove/gallery','GalleryController@destroy')->name('destroy.gallery');
});

Route::get('/home', 'HomeController@index')->name('home');

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
	protected $guarded = [];

	public function getImgAttribute($img)
    {
        if ($img == 'default.png' OR $img == '') {
            return asset('default.jpeg');
        } else {
            return $img;
        }
    }

	//Relationship
    public function client()
    {
    	return $this->hasOne('App\User','id','user_id');
    }
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Image;
use Storage;
use App\Banner;
use App\User;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'banners' => Banner::get()
        ];

        return view('admin.banner.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'clients' => User::role('cliente')->get(),
            'categories' => Category::get(),
        ];

        return view('admin.banner.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $banner = Banner::create($request->except('_token'));
        return redirect()->route('banners.edit',$banner->id)->with('msg-success','Se creo la publicidad.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function show(Banner $banner)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function edit(Banner $banner)
    {
        $data = [
            'banner' => $banner,
            'categories' => Category::get()
        ];

        return view('admin.banner.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Banner $banner)
    {
        if (is_null($request->status)) {
            $request->merge(['status'=>'off']);
        }

        if (is_null($request->status_home_left)) {
            $request->merge(['status_home_left'=>'off']);
        }

        if (is_null($request->status_modal)) {
            $request->merge(['status_modal'=>'off']);
        }

        if (is_null($request->status_home_full)) {
            $request->merge(['status_home_full'=>'off']);
        }

        if (is_null($request->status_article)) {
            $request->merge(['status_article'=>'off']);
        }

        $banner->update($request->all());

        return redirect()->route('banners.edit',[$banner->id])->with('msg-success','Se actualizo correctamente la publicidad.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function destroy(Banner $banner)
    {
        $img_home_left = public_path($banner->img_home_left);
        $img_home_full = public_path($banner->img_home_full);
        $img_article = public_path($banner->img_article);
        $img_modal = public_path($banner->img_modal);

        if(File::exists($img_home_left)) {
            File::delete($img_home_left);
        }
        if(File::exists($img_home_full)) {
            File::delete($img_home_full);
        }
        if(File::exists($img_article)) {
            File::delete($img_article);
        }
        if(File::exists($img_modal)) {
            File::delete($img_modal);
        }

        $banner->delete();
        return redirect()->back()->with('msg-success','Se ha borrado la cuenta publicitaria correctamente.');
    }

    //Imágenes
    public function lateral(Request $request)
    {
        $banner = Banner::find($request->id);

        $this->validate($request, [
            'img' => 'image|mimes:jpeg,png,jpg,gif|max:6048',
        ]);

        //If img
        if ($request->img) {

            //Remove image
            Storage::delete($banner->img_home_left);

            //Upload image
            $imageName = time().'.'.$request->img->extension();  
            $request->img->move(public_path('files/banner'), $imageName);
            $banner->img_home_left = '/files/banner/'.$imageName;
        
            $banner->save();

            return redirect()->back()->with('msg-success','Se ha subido la portada lateral satisfactoriamente.');
        }
    }

    public function full(Request $request)
    {
        $banner = Banner::find($request->id);

        $this->validate($request, [
            'img' => 'image|mimes:jpeg,png,jpg,gif|max:6048',
        ]);

        //If img
        if ($request->img) {

            //Remove image
            Storage::delete($banner->img_home_full);

            //Upload image
            $imageName = time().'.'.$request->img->extension();  
            $request->img->move(public_path('files/banner'), $imageName);
            $banner->img_home_full = '/files/banner/'.$imageName;
        
            $banner->save();

            return redirect()->back()->with('msg-success','Se ha subido la portada horizontal satisfactoriamente.');
        }
    }

    public function modal(Request $request)
    {
        $banner = Banner::find($request->id);

        $this->validate($request, [
            'img' => 'image|mimes:jpeg,png,jpg,gif|max:6048',
        ]);

        //If img
        if ($request->img) {

            //Remove image
            Storage::delete($banner->img_modal);

            //Upload image
            $imageName = time().'.'.$request->img->extension();  
            $request->img->move(public_path('files/banner'), $imageName);
            $banner->img_modal = '/files/banner/'.$imageName;
        
            $banner->save();

            return redirect()->back()->with('msg-success','Se ha subido el modal satisfactoriamente.');
        }
    }

    public function detail(Request $request)
    {
        $banner = Banner::find($request->id);

        $this->validate($request, [
            'img' => 'image|mimes:jpeg,png,jpg,gif|max:6048',
        ]);

        //If img
        if ($request->img) {

            //Remove image
            Storage::delete($banner->img_article);

            //Upload image
            $imageName = time().'.'.$request->img->extension();  
            $request->img->move(public_path('files/banner'), $imageName);
            $banner->img_article = '/files/banner/'.$imageName;
        
            $banner->save();

            return redirect()->back()->with('msg-success','Se ha subido la portada del artículo satisfactoriamente.');
        }
    }
}

resources/views/admin/banner/create.blade.php
@extends('layouts.admin')

@section('title','Agregar cuenta publicitaria')

@section('add-button')
	<a href="{{route('posts.index')}}" class="btn btn-info">Regresar</a>
@endsection

@section('subtitle')
@endsection

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Banner</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
	
	<form method="post" action="{{route('banners.store')}}">
		@csrf
		<div class="col-xl-1 col-lg-2">
			<div class="form-group">
				<label>Estatus:</label><br>
				<input type="checkbox" name="status" data-bootstrap-switch data-on-color="success">
			</div>
		</div>
		<div class="form-group">
			<label>Nombre:</label>
			<input type="text" name="name" class="form-control" required>
		</div>
		<div class="form-group">
			<label>Cliente:</label>
			<select class="form-control" name="user_id">
				@foreach ($data['clients'] as $client)
					<option value="{{$client->id}}">{{$client->name}}</option>
				@endforeach
			</select>
		</div>
		<div class="form-group">
			<label>Categoría:</label>
			<select class="form-control" name="category_id">
				@foreach ($data['categories'] as $category)
					<option value="{{$category->id}}">{{$category->name}}</option>
				@endforeach
			</select>
		</div>
		<button type="submit" class="btn btn-success">Cotinuar</button>
	</form>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('assets/plugins/ckeditor/build/ckeditor.js')}}"></script>
	<script src="{{asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
	<script src="{{asset('assets/plugins/summernote/summernote-bs4.min.js')}}"></script>
	<script>
		switch_init();
	</script>
@endpush

resources/views/admin/banner/edit.blade.php
@extends('layouts.admin-empty')

@section('title','Editar publicidad')

@section('add-button')
	<a href="{{route('banners.index')}}" class="btn btn-danger" style="margin-right: 5px;">Regresar</a>
	<a href="#" id="save" class="btn btn-success">Guardar cambios</a>
@endsection

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Publicidad</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('assets/plugins/owl/assets/owl.carousel.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/plugins/owl/assets/owl.theme.default.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')

	<div class="col-md-12">
	    <div class="card">
	      <div class="card-header">
	        <h3 class="card-title">@yield('subtitle')</h3>
	      </div>
	      <div class="card-body">
	      	@if (Session::has('msg-success'))
			    <div class="alert alert-success">
			        <ul>
			            <li>{!! Session::get('msg-success') !!}</li>
			        </ul>
			    </div>
			@endif
			<form method="post" id="form-global" action="{{route('banners.update',$data['banner']->id)}}"  enctype="multipart/form-data">
				@if ($errors->any())
					<div class="alert alert-danger">
				        <ul>
				           @foreach ($errors->all() as $error)
					           <div>{{$error}}</div>
					     	@endforeach
				        </ul>
				    </div>
				@endif
				@csrf
				{{ method_field('PUT') }}
				<div class="row">
					<div class="col-xl-1 col-lg-2">
						<div class="form-group">
							<label>Estatus:</label><br>
							<input type="checkbox" name="status" {{$data['banner']->status == 'on' ? 'checked':''}} data-bootstrap-switch data-on-color="success">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						<div class="form-group">
							<label>Nombre:</label>
							<input type="text" name="name" class="form-control" value="{{$data['banner']->name}}">
						</div>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Cliente:</label>
							<input type="text" name="name" class="form-control" value="{{$data['banner']->client->name}}" disabled>
						</div>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Categoría:</label>
							<select class="form-control" name="category_id">
								@foreach ($data['categories'] as $category)
									<option value="{{$category->id}}"  {{$data['banner']->category_id == $category->id ? 'selected':''}}>{{$category->name}}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="col-md-3">
						<div class="form-group">
							<label>Url:</label>
							<input type="text" class="form-control" name="url" value="{{$data['banner']->url}}">
						</div>
					</div>
				</div>
				<div class="row">

					@if($data['banner']->category_id != 19)
						<div class="col-xl-3 col-lg-3">
							<div class="form-group">
								<label>Flotante categoría:</label><br>
								<input type="checkbox" name="status_modal" {{$data['banner']->status_modal == 'on' ? 'checked':''}} data-bootstrap-switch data-on-color="success">
							</div>
						</div>
					@endif
					@if($data['banner']->category_id != 19)
						<div class="col-xl-3 col-lg-3">
							<div class="form-group">
								<label>Derecha (Portada):</label><br>
								<input type="checkbox" name="status_home_left" {{$data['banner']->status_home_left == 'on' ? 'checked':''}} data-bootstrap-switch data-on-color="success">
							</div>
						</div>
					@endif
					<div class="col-xl-3 col-lg-3">
						<div class="form-group">
							<label>Horizontal (Portada y Categoría):</label><br>
							<input type="checkbox" name="status_home_full" {{$data['banner']->status_home_full == 'on' ? 'checked':''}} data-bootstrap-switch data-on-color="success">
						</div>
					</div>
					@if($data['banner']->category_id != 19)
						<div class="col-xl-3 col-lg-3">
							<div class="form-group">
								<label>Detalle artículo:</label><br>
								<input type="checkbox" name="status_article" {{$data['banner']->status_article == 'on' ? 'checked':''}} data-bootstrap-switch data-on-color="success">
							</div>
						</div>
					@endif
				</div>
				<button type="submit" class="btn btn-success btn-hidden">Guardar</button>
			</form>
	      </div>
	    </div>
	    <!-- /.card -->
	</div>

	@if($data['banner']->category_id != 19)
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Flotante categoría (600x400)</h3>
				</div>
				<div class="card-body">
					<form action="{{route('upload.modal')}}" enctype="multipart/form-data" method="post">
						@csrf
						<div class="form-group">
							<input type="hidden" name="id" value="{{$data['banner']->id}}">
							<input type="file" name="img" class="form-control"><hr>
							<img src="{{$data['banner']->img_modal}}" class="img-fluid" style="max-width: 200px;">
							<br>
						</div>
						<hr>
						<button type="submit" class="btn btn-primary">Subir</button>
					</form>
				</div>
			</div>
		</div>
	@endif

	@if($data['banner']->category_id != 19)
	<div class="col-md-4">
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Portada derecha (600x400)</h3>
			</div>
			<div class="card-body">
				<form action="{{route('upload.lateral')}}" enctype="multipart/form-data" method="post">
					@csrf
					<div class="form-group">
						<input type="hidden" name="id" value="{{$data['banner']->id}}">
						<input type="file" name="img" class="form-control"><hr>
						<img src="{{$data['banner']->img_home_left}}" class="img-fluid" style="max-width: 200px;">
						<br>
					</div>
					<hr>
					<button type="submit" class="btn btn-primary">Subir</button>
				</form>
			</div>
		</div>
	</div>
	@endif

	<div class="col-md-4">
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Portada horizontal (1100x340)</h3>
			</div>
			<div class="card-body">
				<form action="{{route('upload.full')}}" enctype="multipart/form-data" method="post">
					@csrf
					<div class="form-group">
						<input type="hidden" name="id" value="{{$data['banner']->id}}">
						<input type="file" name="img" class="form-control"><hr>
						<img src="{{$data['banner']->img_home_full}}" class="img-fluid" style="max-width: 200px;">
						<br>
					</div>
					<hr>
					<button type="submit" class="btn btn-primary">Subir</button>
				</form>
			</div>
		</div>
	</div>

	@if($data['banner']->category_id != 19)
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">Detalle artículo (600x400)</h3>
				</div>
				<div class="card-body">
					<form action="{{route('upload.detail')}}" enctype="multipart/form-data" method="post">
						@csrf
						<div class="form-group">
							<input type="hidden" name="id" value="{{$data['banner']->id}}">
							<input type="file" name="img" class="form-control"><hr>
							<img src="{{$data['banner']->img_article}}" class="img-fluid" style="max-width: 200px;">
							<br>
						</div>
						<hr>
						<button type="submit" class="btn btn-primary">Subir</button>
					</form>
				</div>
			</div>
		</div>
	@endif
	
@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
	<script>
		switch_init();
	</script>
@endpush

resources/views/admin/banner/index.blade.php
@extends('layouts.admin')

@section('title','Publicidad')

@section('subtitle','Todas los banners')

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Banners</li>
@endsection

@section('add-button')
	<li class="nav-item d-none d-sm-inline-block">
	    <a href="{{route('banners.create')}}" class="btn btn-success" style="color:#fff;">Agregar</a>
	</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')

	@if (Session::has('msg-success'))
	    <div class="alert alert-success">
	        <ul>
	            <li>{!! Session::get('msg-success') !!}</li>
	        </ul>
	    </div>
	@endif

	<table id="datatable" class="table table-striped table-bordered table-sm">
      <thead class="thead-light">
          <tr class="text-center">
            <th>Nombre</th>
            <th>Cliente</th>
            <th>Fecha</th>
            <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
      		@foreach ($data['banners'] as $banner)
	            <tr class="text-center">
	                <td>{{$banner->name}}</td>
	                <td>{{$banner->client->name}}</td>
	                <td>{{$banner->created_at->format('d-m-Y')}}</td>
	                <td>
	                	<ul>
	                		<li>
	                			<a href="{{route('banners.edit',$banner->id)}}" class="btn btn-success btn-xs">Editar</a>
	                		</li>
	                		@role('admin')
	                		<li>
	                			<form method="POST" action="{{ route('banners.destroy',$banner->id) }}">
								    @csrf
								    {{ method_field('delete') }}
								    <button type="submit" class="btn btn-danger btn-xs">Eliminar</button> 
								</form>	
	                		</li>
	                		@endrole
	                	</ul>
	                </td>
	            </tr>
            @endforeach
      </tbody>
    </table>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('adminlte/plugins/datatables/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
	<script>
		datatables();
	</script>
@endpush

resources/views/admin/banner/show.blade.php
@extends('layouts.admin')

@section('title',$post->name)

@section('col','col-12')

@section('subtitle')
	<strong>Fecha de creación:</strong> {{$post->created_at->format('d-m-Y')}}
@endsection

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item"><a href="{{route('posts.index')}}">Noticias</a></li>
  <li class="breadcrumb-item active">{{$post->name}}</li>
@endsection

@section('content')
	<p>
		<strong>Nombre:</strong> {{$post->name}}<br>
		<strong>Estatus:</strong> {{$post->status}}<br>
		<strong>Categoría:</strong> {{$post->name}}<br>
		<strong>Imagen:</strong> {{$post->img}}<br>
		<strong>Descripción:</strong> <br>{{$post->description}}
	</p>
@endsection

@section('footer')
	<a href="{{route('posts.index')}}" class="btn btn-info">Regresar</a>
@endsection

@push('js')
@endpush