routes/web.php
<?php
//Auth
Auth::routes([
	'verify' => false,
	'register' => false
]);

Route::get('image/{filename}', 'AdminController@displayImage')->name('image.displayImage');

//Front
Route::get('/','FrontController@index')->name('front.index');
Route::get('noticias/{cat}/{name}','FrontController@single')->name('front.single');
Route::get('categoria/{cat}','FrontController@category')->name('front.category');
Route::get('categorias/{user}/{name}','FrontController@categoryUser')->name('front.category.user');
Route::get('contacto','FrontController@contact')->name('front.contact');
Route::get('busqueda','FrontController@search')->name('front.search');
Route::any('banners/{id}/{position}','FrontController@url')->name('front.url');
Route::post('save_contact','FrontController@save_contact')->name('front.save.contact');

//Admin
Route::group(['prefix' => 'admin'], function(){
	Route::get('/','AdminController@index')->name('admin.index');
	Route::post('users/upload','UserController@upload_image')->name('upload.user');
    Route::resource('users','UserController');
	Route::resource('leads','LeadController');
	Route::resource('clients','ClientController');
	Route::resource('clientspost','ClientPostController');
	Route::post('uploads/lateral','BannerController@lateral')->name('upload.lateral');
	Route::post('uploads/full','BannerController@full')->name('upload.full');
	Route::post('uploads/detail','BannerController@detail')->name('upload.detail');
	Route::post('uploads/modal','BannerController@modal')->name('upload.modal');
	Route::resource('banners','BannerController');
	Route::post('uploads/image','PostController@upload_image')->name('upload.image');
	Route::get('posts/list','PostController@getPosts')->name('posts.list');
	Route::get('posts/delete/{id}','PostController@delete')->name('posts.delete');
	Route::get('post/restore/{id}','PostController@restore')->name('post.restore');
	Route::resource('posts','PostController');
	Route::resource('systems','SystemController');
	Route::resource('categories','CategoryController');

	//Gallery
	Route::post('uploads/gallery','GalleryController@upload_gallery')->name('upload.gallery');
	Route::any('remove/gallery','GalleryController@destroy')->name('destroy.gallery');
});

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Carbon\Carbon;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','rfc','direction','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getDateAttribute(){
        $date = Carbon::parse($this->created_at);
        return $date->format('d-m-Y');
    }


    //Relationship
    public function posts()
    {
        return $this->hasMany('App\Post', 'user_id', 'id');
    }

    public function banners()
    {
        return $this->hasMany('App\Banner', 'user_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Image;
use Storage;
use App\User;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use role;

class UserController extends Controller
{
    public function index()
    {
        $users = User::role(['admin','editor','columnista'])->get();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
        ]);

        // Le asignamos el rol de Cliente
        if ($request->rol == 'editor') {
            $user->syncRoles('editor');
        } elseif($request->rol == 'columnista') {
            $user->syncRoles('columnista');
        } elseif($request->rol == 'cliente') {
            $user->syncRoles('cliente');
        } else {
            $user->syncRoles('admin');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->bio = $request->bio;

        if ($request->password && $request->password_confirmation) {

            $request->validate([
              'password' => 'required|string|min:6|confirmed',
              'password_confirmation' => 'required',
            ]);

            $user->password = bcrypt($request->password);
        }

        $user->save();

        // Le asignamos el rol de Cliente
        if ($request->rol == 'editor') {
            $user->syncRoles('editor');
        } elseif($request->rol == 'columnista') {
            $user->syncRoles('columnista');
        } elseif($request->rol == 'cliente') {
            $user->syncRoles('cliente');
        } else {
            $user->syncRoles('admin');
        }

           
        //If img
        if ($request->img) {

            $this->validate($request, [
                'img' => 'image|mimes:jpeg,png,jpg|max:6048',
            ]);

            //Remove image
            $image_path = public_path($user->img);
            if(File::exists($image_path)) {
                File::delete($image_path);
            }

            $file = $request->file('img');
            $path = $file->hashName('public/files/user');
            $image = Image::make($file)->resize(null, 600, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put($path, (string) $image->encode());
            $url = Storage::url($path);    

            //Update img
            $user->img = $url;
            $user->save();

            return redirect()->back()->with('msg-success','Se ha subido la imagen correctamente.');
        }

        return redirect()->back()->with('msg-success','Se actualiza los datos de usuario.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user->posts->count() >= 1) {
            return redirect()->back()->with('msg-error','No se puede borrar el usario, ya que cuenta con noticias.');
        } else {
            $user->delete();
            return redirect()->back()->with('msg-success','Se ha borrado el usuario satisfactoriamente.');
        }
    }

    public function upload_image(Request $request)
    {
        //Obtenemos el post
        $post = Post::find($request->id);

        $this->validate($request, [
            'img' => 'image|mimes:jpeg,png,jpg|max:6048',
        ]);

        //If img
        if ($request->img) {

            //Remove image
            $image_path = public_path($post->img);
            if(File::exists($image_path)) {
                File::delete($image_path);
            }

            $file = $request->file('img');
            $path = $file->hashName('public/files/post');
            $image = Image::make($file)->resize(null, 600, function ($constraint) {
                $constraint->aspectRatio();
            });
            Storage::put($path, (string) $image->encode());
            $url = Storage::url($path);    

            //Update img
            $post->img = $url;
            $post->save();

            return redirect()->back()->with('msg-success','Se ha subido la portada satisfactoriamente.');
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('title','Agregar usuario')

@section('add-button')
	<a href="{{route('users.index')}}" class="btn btn-info">Regresar</a>
@endsection

@section('subtitle')
@endsection

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Usuario</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
	
	<form method="post" action="{{route('users.store')}}">
		@csrf
		<div class="form-group">
			<label>Nombre:</label>
			<input type="text" name="name" class="form-control" required>
		</div>
		<div class="form-group">
			<label>Correo electrónico:</label>
			<input type="email" name="email" class="form-control" required>
		</div>
		<div class="form-group">
			<label>Rol:</label>
			<select class="form-control" name="rol" required>
				<option value="admin">Administrador</option>
				<option value="editor">Editor</option>
				<option value="columnista">Columnista</option>
				<option value="cliente">Cliente</option>
			</select>
		</div>
		<div class="form-group">
			<label>Contraseña:</label>
			<input type="password" name="password" class="form-control" required>
		</div>
		<button type="submit" class="btn btn-success">Agregar usuario</button>
	</form>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
	<script src="{{asset('assets/plugins/summernote/summernote-bs4.min.js')}}"></script>
	<script>
		switch_init();
		summernote_init();
	</script>
@endpush

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title','Editar usuario')

@section('add-button')
	<a href="{{route('users.index')}}" class="btn btn-danger" style="margin-right: 5px;">Cancelar</a>
	<a href="#" id="save" class="btn btn-success">Guardar cambios</a>
@endsection

@section('subtitle')
@endsection

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Usuario</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.css')}}">
@endpush

@section('content')
	
	<form method="post" id="form-global" action="{{route('users.update',$user->id)}}"  enctype="multipart/form-data">
		@if ($errors->any())
	     	@foreach ($errors->all() as $error)
		     	<div class="alert alert-danger">
			        <ul>
			            <li>{{$error}}</li>
			        </ul>
			    </div>
	     	@endforeach
		@endif
		@if (Session::has('msg-success'))
		    <div class="alert alert-success">
		        <ul>
		            <li>{!! Session::get('msg-success') !!}</li>
		        </ul>
		    </div>
		@endif
		@csrf
		{{ method_field('PUT') }}
		<div class="form-group">
			<label>Nombre:</label>
			<input type="text" name="name" class="form-control" value="{{$user->name}}">
		</div>
		<div class="form-group">
			<label>Correo electrónico:</label>
			<input type="text" name="email" class="form-control" value="{{$user->email}}">
		</div>
		<hr>
		<div class="row">
			<div class="col-xl-12">
				<h5>Cambiar contraseña:</h5>
			</div>
			<div class="col-xl-6">
				<div class="form-group">
					<label>Contraseña:</label>
					<input type="password" name="password" class="form-control">
				</div>
			</div>
			<div class="col-xl-6">
				<div class="form-group">
					<label>Repetir contraseña:</label>
					<input type="password" name="password_confirmation" class="form-control">
				</div>
			</div>
		</div>
		<hr>
		@role('admin')
			<div class="form-group">
				<label>Roles:</label>
				<select class="form-control" name="rol" required>
					@php
						$rol = $user->roles->pluck('name');
					@endphp
					<option value="admin" @if ($rol[0] == 'admin') selected @endif>Administrador</option>
					<option value="editor" @if ($rol[0] == 'editor') selected @endif>Editor</option>
					<option value="columnista" @if ($rol[0] == 'columnista') selected @endif>Columnista</option>
					<option value="cliente" @if ($rol[0] == 'cliente') selected @endif>Cliente</option>
				</select>
			</div>
		@endrole
		<div class="form-group">
			<label>Biografía:</label>
			<textarea class="form-control summernote" name="bio">{!!$user->bio!!}</textarea>
		</div>
		<div class="form-group">
			<label>Imagen:</label>
			<input type="file" name="img" class="form-control"><hr>
			<img src="{{$user->img}}" class="img-fluid" style="max-width: 300px;">
		</div>
		<button type="submit" class="btn btn-success btn-hidden">Guardar</button>
	</form>

@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
	<script src="{{asset('assets/plugins/summernote/summernote-bs4.min.js')}}"></script>
	<script>
		summernote_init();
		switch_init();
	</script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('title','Usuarios')

@section('subtitle','Todos los usuarios')

@section('col','col-12')

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item active">Noticias</li>
@endsection

@section('add-button')
	<li class="nav-item d-none d-sm-inline-block">
	    <a href="{{route('users.create')}}" class="btn btn-success" style="color:#fff;">Agregar</a>
	</li>
@endsection

@push('css')
	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  	<link rel="stylesheet" href="{{asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')
	@if (Session::has('msg-success'))
	    <div class="alert alert-success">
	        <ul>
	            <li>{!! Session::get('msg-success') !!}</li>
	        </ul>
	    </div>
	@endif
	<table id="datatable" class="table table-striped table-bordered table-sm">
      <thead class="thead-light">
          <tr class="text-center">
          	<th>#</th>
            <th>Nombre</th>
            <th>Fecha de registro</th>
            <th>Rol</th>
            <th>Acciones</th>
          </tr>
      </thead>
      <tbody>
      		@foreach ($users as $user)
	            <tr class="text-center">
	            	<td>{{$user->id}}</td>
	                <td>{{$user->name}}</td>
	                <td>{{$user->date}}</td>
	                <td>
	                	@php
	                		$roles = $user->getRoleNames();
	                	@endphp
	                	@foreach ($roles as $rol)
                			@if ($rol == 'admin')
                				<span class="badge badge-success">Administrador</span>
                			@elseif($rol == 'columnista')
                				<span class="badge badge-info">{{$rol}}</span>
                			@elseif($rol == 'cliente')
                				<span class="badge badge-warning">{{$rol}}</span>
                			@else
                				<span class="badge badge-primary">{{$rol}}</span>
                			@endif
                		@endforeach
	                </td>
	                <td>
	                	<ul>
	                		<li>
	                			<a href="{{route('users.edit',$user->id)}}" class="btn btn-success btn-xs">Editar</a>
	                		</li>
	                		<li>
	                			<form method="POST" action="{{ route('users.destroy',$user->id) }}">
								    {{ csrf_field() }}
								    {{ method_field('delete') }}
								    <button type="submit" class="btn btn-danger btn-xs">Eliminar</button> 
								</form>	
	                		</li>
	                	</ul>
	                </td>
	            </tr>
            @endforeach
      </tbody>
    </table>
@endsection

@section('footer')
@endsection

@push('js')
	<script src="{{asset('adminlte/plugins/datatables/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
	<script>
	  datatables();
	</script>
@endpush

resources/views/admin/user/show.blade.php
@extends('layouts.admin')

@section('title',$post->name)

@section('col','col-12')

@section('subtitle')
	<strong>Fecha de creación:</strong> {{$post->created_at->format('d-m-Y')}}
@endsection

@section('breadcrumb')
  <li class="breadcrumb-item"><a href="{{route('admin.index')}}">Administrador</a></li>
  <li class="breadcrumb-item"><a href="{{route('posts.index')}}">Noticias</a></li>
  <li class="breadcrumb-item active">{{$post->name}}</li>
@endsection

@section('content')
	<p>
		<strong>Nombre:</strong> {{$post->name}}<br>
		<strong>Estatus:</strong> {{$post->status}}<br>
		<strong>Categoría:</strong> {{$post->name}}<br>
		<strong>Imagen:</strong> {{$post->img}}<br>
		<strong>Descripción:</strong> <br>{{$post->description}}
	</p>
@endsection

@section('footer')
	<a href="{{route('posts.index')}}" class="btn btn-info">Regresar</a>
@endsection

@push('js')
@endpush